### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Wotuu** [wowdev/wow-listfile#109]
Hi,

I'm looking for an updated listfile which contains BfA assets, I tried running some scripts in this repo, but even reading them gives me no clue what I'm supposed to do with it to get the updated listfile. Can anyone point me in the right direction? I want to extract some BfA assets which are clearly in-game but I cannot find them whatsoever.

Thank you in advance.

**Comment by Marlamin** [comment]
[Go here](https://github.com/wowdev/wow-listfile/blob/master/listfile.txt), right click "Download" and save it where you want to.

**Comment by Wotuu** [comment]
Hi Marlamin, perhaps I wasn't clear enough, but I know what to do with the listfile. It's just that it's not updated. I did some searching around the net but keep coming back here so there must be something, someone updating the listfile to contain assets from a new expansion.  The listfile you linked does _not_ have the assets I'm looking for unless they're named differently from previous expansions. To be more precises, I'm looking for dungeon floor .blp tiles used in the in-game map. I tried adding a dungeon  manually to the listfile but that didn't work.

So again, I'm wondering how the listfile gets created in the first place, and how I could perhaps update it so I can extract the assets. I thought I could generate the listfile with this project but I haven't managed that since the .sh files are a bit of a mystery to me (I only have basic bash knowledge).

Thank you once again.

**Comment by bloerwald** [comment]
People make more or less educated guesses, check if the guess is a file that exists, and if yes, push it to the repository. 

You can guess just as wel, especially if you are sure that a file should be called some specific way but there is no such file.

The check_files scripts can be used to easily verify if a guess is correct.

**Comment by Marlamin** [comment]
@Wotuu My bad, that's what I get for looking at issues that late. I probably shouldn't do that. :D

**Comment by Wotuu** [comment]
I'm trying to just the check_files.sh file, but what exactly do I supply it?

`./marlamin-check_files.sh interface/worldmap/ataldazar/ataldazar1.blp`

gives me File not Found. I see it does a curl request to your server to check if it's okay, but it shouldn't read what I'm trying to pass, it's an entry that I'm trying to check. If that's wrong, what _do_ I pass to it? There's no single source for WoW's data, it's a split archive.

I'm just confused about this all, I mean why is a listfile even necessary? Why is a file necessary to look up some indices in another file? Can't you just gather the indices from the file itself and not need the listfile? When I have time I'll take a look at the tool that opens the WoW data files but for now I don't have that luxury.  It just seems a bit strange to me.

**Comment by bloerwald** [comment]
Checkfiles takes a file with one filename per line. Checkfiles-pipe takes one filename per line on stdin.

The listfile isn’t needed, you can open files by id or content hash as well. Alternatively you can use a filename hash, for which you either need the hash, which is a pretty shit thing to remember, or the unhashed filename. The listfile is for exactly those unhashed filenames.

**Comment by Wotuu** [comment]
Thank you for the reply. I found your website at https://bnet.marlam.in/ from the .sh files, I tried some of what I thought should be valid filenames, but they all end up with invalid result. What are my options here now? I can't keep guessing for all dungeons in hopes I get one correct. Is it really just guessing at this point? Because that'd put a serious halt on my operations. I'd have to resort to screenshots which I really don't want.

How does your website see if, say, /interface/worldmap/ataldazar/ataldazar1.blp is correct or not? If it knows it's correct, it shouldn't need me to tell it right? Sorry that I'm asking so much questions, just trying to wrap my head around this mystery. Is the lookup the hashed string of what you're supplying in the page?

**Comment by Marlamin** [comment]
The site checks based on filename hashes supplied by Blizzard. If the filename hash matches, it adds it to the listfile (and will appear in this repo next sync, or if you don't want to wait you can download the listfile from the site too). World map files should all have filenames though as Blizzard supplies filenames for these (for now). Try searching around a bit [here](https://bnet.marlam.in/files.php#search=&page=1).

**Comment by Wotuu** [comment]
I found all the dungeon maps of the new expansion, cheers all! The ones that I was looking for had completely different names (Atal'Dazar -> cityofgold), there were a bunch that weren't as hidden but I just didn't bother to look since the 2-3 I tried had different names than I was suspecting. Glad to see I got the map files now, my work can continue.

**Comment by bloerwald** [comment]
You may want to share the new filenames you found, @wotuu. Thanks.

**Comment by Wotuu** [comment]
I didn't find any new names, they were already in the listfile. If you want
the conversions from key -> dungeonname I can give you a table no problem,
though I don't think you're after that :).

**Comment by Marlamin** [comment]
What are you doing if I might ask?

**Comment by Wotuu** [comment]
I am making a website where people can enter their favorite routes for
dungeons for Mythic+ in BfA. Taking into account mobs, %-age etc. For that,
I load the .blp files, run them through a bunch of converters, and display
them in a Leaflet map.

**Comment by Marlamin** [comment]
Cool! You should probably use the world map related DBCs though instead of relying on filenames. I have a mostly working implementation (minus phased maps) [here](https://github.com/Marlamin/WoWFormatTest/blob/master/WorldMapCompiler/Program.cs).

**Comment by Wotuu** [comment]
I'm not relying on the filenames whatsoever. I extracted the data, put em
through my program and now I have some 10k pngs which Leaflet can use to
display the map. Works a charm. It's not going to be an addon, it's a
website so I will be self-hosting the images.

**Comment by Marlamin** [comment]
Righto. Good luck!

**Comment by Wotuu** [comment]
Just a small update, I managed to get everything up and running, you can view the project on https://keystone.guru/. Thanks again for the help!
