### ISSUE TITLE
New files for 8.1 ptr

### ISSUE THREAD

**Issue by jimmsta** [wowdev/wow-listfile#111]
World\wmo\Azeroth\Buildings\Stormwind\SW_Harbor_Lighthouse_000_lod1.blp
World\wmo\Azeroth\Buildings\Stormwind\SW_Harbor_Lighthouse_000_lod2.blp
world\expansion07\doodads\8xp_uthershrine_statue01hammerbook.blp
world\generic\passivedoodads\thanksgiving\8_tgiving_plates.blp
WORLD\WMO\DUNGEON\SEAPRIESTDUNGEON\8DU_SeaPriest_JunctionInterior05.wmo
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_billboardmap01.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_billboardmap04.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_tent01-02.blp
world\expansion07\doodads\human\8hu_bankdoor_gold256.blp
world\expansion07\doodads\human\8hu_kultiras_statuebase01flaguvs.blp
world\expansion07\doodads\human\firearm_2h_riflec_02.blp
world\expansion07\doodads\kultiraszone\8kul_citydirttile01.blp
world\expansion07\doodads\riverzone\6ng_waterfall_04_rot.blp
WORLD\WMO\ZULDAZAR\DESERTZONE\8DES_CaveMicro04_water.wmo
world\expansion07\doodads\serpentine\8se_serpentine_trollskull02.blp
world\expansion07\doodads\zandalaritroll\8tr_zandalari_canopy_largedrapes01.blp
world\expansion07\doodads\zandalaritroll\8tr_zandalari_canopy_mediumdrapes01.blp
world\expansion07\doodads\zandalaritroll\8tr_zandalari_ship_doorhatch01planeao1.blp
world\expansion07\doodads\zuldazarzone\6ng_waterfall_04_rot.blp
world\expansion07\doodads\8xp_warrock_01.blp
world\expansion07\doodads\8xp_warrock_02.blp
spells\glow_painted_grey_ba.blp
spells\glow_painted_shadow_ba.blp
World\wmo\Dungeon\ZuldazarRaid\8DU_ZuldazarRaid_Main01.wmo
WORLD\WMO\ZULDAZAR\TROLL\8TR_Zandalari_ShipMedWrecked01.wmo
WORLD\WMO\ZULDAZAR\TROLL\8TR_Zandalari_ShipMedWrecked02.wmo
dungeons\textures\8du_goldcity\8du_goldcity_gate_dark02.blp
dungeons\textures\8tr_zandalari\8tr_brickwall04_goldcoin.blp
dungeons\textures\8tr_zandalari\8tr_stonelattice01_emissive.blp
dungeons\textures\8tr_zandalari\ship_psds\8tr_ship_woodwrecked01.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_centerpiece01.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_centerpiece02.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_coins01.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_coins02.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_columntrim01.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_columntrim02.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_columntrim03.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_columntrim04.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_entrancerubble01.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_goldtrim01.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_grate01.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_grate02.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_loacalendar01.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_du_windowshadow01.blp
dungeons\textures\8tr_zandalari\zuldazar_raid\8tr_goldslab02.blp
world\environment\doodad\zandalari\8tr_zandalari\8tr_zandalari_market\8tr_zandalari_marketstall_cloth01.blp
world\environment\doodad\zandalari\8tr_zandalari\8tr_zandalari_market\8tr_zandalari_marketstall_cloth02.blp
world\environment\doodad\zandalari\8tr_zandalari\8tr_zandalari_market\8tr_zandalari_marketstall_pillar01wood.blp
world\environment\doodad\zandalari\8tr_zandalari\8tr_zandalari_rugs\8tr_zandalari_rugs01.blp
world\environment\doodad\zandalari\8tr_zandalari\8tr_zandalari_shipprops\8tr_zandalari_ship_doorhatch01.blp
world\expansion07\doodads\dungeon\doodads\7fx_alphamask_glow_mint.blp
world\expansion07\doodads\dungeon\doodads\7fx_waveyhalf_mask.blp
world\expansion07\doodads\dungeon\doodads\7fx_wind_rift_double_thick_glow.blp
world\expansion07\doodads\dungeon\doodads\7fx_wind_rift_glow_01.blp
world\expansion07\doodads\dungeon\doodads\8du_zuldazar_coin01.blp
world\expansion07\doodads\dungeon\doodads\8du_zuldazar_coin01.m2
world\expansion07\doodads\dungeon\doodads\8du_zuldazar_coin02.blp
world\expansion07\doodads\dungeon\doodads\8du_zuldazar_coin02.m2
world\expansion07\doodads\dungeon\doodads\8du_zuldazar_coin02_spec.blp
world\expansion07\doodads\dungeon\doodads\8du_zuldazar_largedoor01_diffuse.blp
world\expansion07\doodads\dungeon\doodads\8du_zuldazar_mask_face01.blp
world\expansion07\doodads\dungeon\doodads\8du_zuldazar_mask_horns01.blp
world\expansion07\doodads\dungeon\doodads\8du_zuldazar_mask_nose01.blp
world\expansion07\doodads\dungeon\doodads\8du_zuldazarraid_rastakahn_throne01.blp
world\expansion07\doodads\dungeon\doodads\8du_zuldazarraid_rastakahn_throne01.m2
world\expansion07\doodads\dungeon\doodads\8du_zuldazarraid_rastakahn_throne02.blp
world\expansion07\doodads\dungeon\doodads\8fx_loastatue_glow.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloabase01.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloabase02.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloafrog01.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloafrog01_glow.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloapterrordax01.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloaraptor01.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloaraptor01_glow.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloathunderlizard01.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloathunderlizard01_glow.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloatiger01.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloatiger01_glow.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloatrollbwonsamdi01.blp
world\expansion07\doodads\dungeon\doodads\8tr_zandalari_statueloatrollbwonsamdi01_glow.blp
world\expansion07\doodads\dungeon\doodads\armorreflect_organic01.blp
world\expansion07\doodads\dungeon\doodads\ember_offset_blue.blp
world\expansion07\doodads\dungeon\doodads\fire_bright_mod2x_a_blue.blp
world\expansion07\doodads\dungeon\doodads\oldglass3.blp
world\expansion07\doodads\dungeon\doodads\spirit_tr1.blp
world\expansion07\doodads\dungeon\doodads\t_vfx_flare09.blp
world\expansion07\doodads\dungeon\doodads\verticalgradient_caustic_01.blp
world\expansion07\doodads\dungeon\doodads\worc_gold_reflect_goldcolor.blp
world\expansion07\doodads\dungeon\doodads\yellow.blp
world\expansion07\doodads\fx\7fx_arcane_starfield_holy.blp
world\expansion07\doodads\fx\7fx_starfield_blue_ahard.blp
world\expansion07\doodads\fx\8fx_zuldazar_coins_singleflip.blp
world\expansion07\doodads\fx\8fx_zuldazar_coins_singleflip_02.blp
WORLD\WMO\DUNGEON\SEAPRIESTRAID\8DU_SeaPriestRaid_DungeonCap01.wmo
WORLD\WMO\DUNGEON\SEAPRIESTRAID\8DU_SeaPriestRaid_Main01.wmo
WORLD\WMO\DUNGEON\SEAPRIESTDUNGEON\8DU_SeaPriest_JunctionInterior06.wmo
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_blend01.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_blend02.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_blend02-emissive.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_bones.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_bones_blend.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_bossfloor1.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_bossfloor1-blend.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_ceiling.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_ceiling-spheres.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_ceiling-spheres-emissive.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_eye.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_eye-big.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_eye-open.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_eyeroom_jaggedlip.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_floor.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_floor02.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_floor02b_tunnel.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_floor2.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_floor_02-darksinew.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_frontship1.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_frontship2.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_frontship3.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_mainroom-stairplatform.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_platform.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_platform-eyestructure.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_shipwood1.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_shipwood2.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_tooth.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_tunnel-blend.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_tunnel-wall-eyes.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_wall_01.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_wall_01_drops.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_wall_01_eyeroom.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_wall_01_eyeroom-emissive.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_wall_01_faded.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_wall_01_ridged.blp
dungeons\textures\8du_seapriest\8du_seapriestraid\8du_seapriestraid_wall_03.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_bigeye01.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_bigeye01.m2
world\expansion07\doodads\dungeon\doodads\8du_seapriest_bigeye01b.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_bigeye01b_g.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_bigeye_env02.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_eye01.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_eye01.m2
world\expansion07\doodads\dungeon\doodads\8du_seapriest_eye01_g.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_goo01.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_goo01.m2
world\expansion07\doodads\dungeon\doodads\8du_seapriest_goo02flow.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_goo03horizontal.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_goo_env.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_goo_scrolling01.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_mod2xgray.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_movingorgan01.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriest_movingorgan01.m2
world\expansion07\doodads\dungeon\doodads\8du_seapriestraid_floor2_flipalpha.blp
world\expansion07\doodads\dungeon\doodads\8du_seapriestraid_tooth_flipalpha.blp
world\expansion07\doodads\dungeon\doodads\arcane_wisps_purple_alphagain.blp
world\expansion07\doodads\dungeon\doodads\cloud_soft_painterly02a.blp
world\expansion07\doodads\dungeon\doodads\orbreflectdark_small02a.blp
world\expansion07\doodads\dungeon\doodads\prettycolors3.blp
tileset\expansion07\warfronts\8drk_warfronts_rock01_512.blp
WORLD\WMO\DUNGEON\KEZANDUNGEON\8DU_Kezan_Horde_Goblin_LaunchPad02.wmo
tileset\expansion07\warfronts\8drk_warfronts_sand01_512.blp
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_LeafyBush_A01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_BerryBush_B01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_PurpleTree_B01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_ThinPineTreeGreen_B01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Log_B01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_ThinPineTreeGreen_C01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Grass_A02.m2
WORLD\WMO\ZULDAZAR\FORSAKEN\8FK_Forsaken_ShipLarge01.wmo
tileset\expansion07\warfronts\8drk_warfronts_dirt01_512.blp
tileset\expansion07\warfronts\8drk_warfronts_pebbles01_256.blp
tileset\expansion07\warfronts\8drk_warfronts_flowerbed01_512.blp
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_TreeTrunk_A03.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_GreenPineTree_B01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_TreeTrunk_A02.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_TreeTrunk_A01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Rock_A01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_YellowPineTree_A01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Rock_A02.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_TreeTrunkRoots_A01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Bush_B04.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Bush_B02.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Bush_B01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_PurpleTreeRoots_C01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_ThinPineTree_C01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_DeadPineTree_A01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_CoastalTree_D01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Bush_B05.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_CoastalTree_D02.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Bush_B03.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_DeadPineTreeRoots_A01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_FallenTree01.m2
tileset\expansion07\warfronts\8drk_warfronts_grass01_512.blp
tileset\expansion07\warfronts\8drk_warfronts_grass02_512.blp
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_Log_B02.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_PurpleTree_C01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_RedPineTree_B01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_ThinPineTreeRoots_C01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_GreenTree_B01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_GreenPineTreeRoots_C01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_YellowPineTreeRoots_B01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_BurntStoneTree_C01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_BurntStoneTree_B01.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_Barricade01.m2
WORLD\WMO\KULTIRAS\NIGHTELF\8NE_PvP_WarsongBG_House01.wmo
tileset\expansion07\warfronts\8drk_warfronts_road01_512.blp
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_FallenTree02.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_BurntStoneTree_B02.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_BlightContainer02.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_BlightContainer01.m2
WORLD\WMO\KULTIRAS\NIGHTELF\8NE_Nightelf_InnBroken01.wmo
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_StormTornPineTree_D01.m2
WORLD\EXPANSION07\DOODADS\DARKSHORE\8DRK_Warfronts_StormTornPineTree_D02.m2
dungeons\textures\8fk_forsaken\8fk_metaltrim01.blp
dungeons\textures\8fk_forsaken\8fk_shipplanks01.blp
dungeons\textures\8wsg_warsonggulch\8swg_wall01.blp
dungeons\textures\8wsg_warsonggulch\8swg_wall01dark.blp
dungeons\textures\8wsg_warsonggulch\8swg_woodtrims03.blp
dungeons\textures\8wsg_warsonggulch\8wsg_beamend01.blp
dungeons\textures\8wsg_warsonggulch\8wsg_ceiling01.blp
dungeons\textures\8wsg_warsonggulch\8wsg_columnbase01.blp
dungeons\textures\8wsg_warsonggulch\8wsg_roof01.blp
dungeons\textures\8wsg_warsonggulch\8wsg_roof02.blp
dungeons\textures\8wsg_warsonggulch\8wsg_roofgold01.blp
dungeons\textures\8wsg_warsonggulch\8wsg_stonetrims01.blp
dungeons\textures\8wsg_warsonggulch\8wsg_window01.blp
dungeons\textures\8wsg_warsonggulch\8wsg_window02.blp
dungeons\textures\8wsg_warsonggulch\8wsg_woodbeams01.blp
dungeons\textures\8wsg_warsonggulch\8wsg_woodbeams01_edge.blp
dungeons\textures\8wsg_warsonggulch\8wsg_woodbeams02.blp
dungeons\textures\8wsg_warsonggulch\8wsg_woodbeams02_end.blp
dungeons\textures\8wsg_warsonggulch\8wsg_woodtrims02.blp
tileset\expansion07\warfronts\8drk_warfronts_dirt01_512_h.blp
tileset\expansion07\warfronts\8drk_warfronts_dirt01_512_s.blp
tileset\expansion07\warfronts\8drk_warfronts_grass01_512_h.blp
tileset\expansion07\warfronts\8drk_warfronts_grass01_512_s.blp
tileset\expansion07\warfronts\8drk_warfronts_grass02_512_h.blp
tileset\expansion07\warfronts\8drk_warfronts_grass02_512_s.blp
tileset\expansion07\warfronts\8drk_warfronts_road01_512_h.blp
tileset\expansion07\warfronts\8drk_warfronts_road01_512_s.blp
tileset\expansion07\warfronts\8drk_warfronts_rock01_512_h.blp
tileset\expansion07\warfronts\8drk_warfronts_rock01_512_s.blp
world\expansion07\doodads\8drk_burnedoutteldrassil01.blp
world\expansion07\doodads\8drk_burnedoutteldrassil03.blp
world\expansion07\doodads\8drk_burnedoutteldrassil_smoke01.blp
world\expansion07\doodads\8drk_burnedoutteldrassil_smokemask01.blp
world\expansion07\doodads\8drk_burnedoutteldrassil_smokemask02.blp
world\expansion07\doodads\8drk_burnedoutteldrassil_smokemask03.blp
world\expansion07\doodads\8drk_burnedoutteldrassil_smokemask04.blp
world\expansion07\doodads\8drk_fogwall01.blp
world\expansion07\doodads\8drk_fogwall02.blp
world\expansion07\doodads\8xp_goblin_azerite_payload.blp
world\expansion07\doodads\8xp_goblin_doomglow.blp
world\expansion07\doodads\8xp_goblin_doomrocket.blp
world\expansion07\doodads\darkshore\8drk_rock01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_berrybush_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_bush_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_bush_02.blp
world\expansion07\doodads\darkshore\8drk_warfronts_bush_03.blp
world\expansion07\doodads\darkshore\8drk_warfronts_coastaltrees_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_grass_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_greentreecanopy_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_leafybush_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_purpletreecanopy_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_purpletreecanopy_02.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treebark_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treebark_02.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treebark_03.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treebark_04.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treebark_burnt.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treecanopies_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treecanopies_02.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treecanopies_03.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treecanopies_04.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treecanopies_05.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treecanopies_06.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treecanopies_burnt.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treecanopygreen_01.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treecanopygreen_02.blp
world\expansion07\doodads\darkshore\8drk_warfronts_treetrunk_01.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_hazardlights1_diff.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_hazardlights1_red_emis.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_hazardlights1_yellow_emis.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_hazardlights2_diff.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_machinemap01.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_machinemap02.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_machinemap03.blp
world\expansion07\doodads\dungeon\doodads\8du_venturecompany_machinemap04.blp
world\expansion07\doodads\forsaken\8fk_forsaken_barricademap01.blp
world\expansion07\doodads\forsaken\8fk_forsaken_barricademap02.blp
world\expansion07\doodads\forsaken\8fk_forsaken_barricademap03.blp
world\expansion07\doodads\forsaken\nex_envmap01t.blp
world\expansion07\doodads\forsaken\temp_8fk_forsaken_military_props.blp
world\expansion07\doodads\genericglow64.blp
World\Generic\PVP\WarsongGulch\8WSG_Ashenvale_Walls03.m2
World\Generic\PVP\WarsongGulch\8WSG_Ashenvale_Walls02.m2
World\Generic\PVP\WarsongGulch\8WSG_Ashenvale_Walls01.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_Brazier01.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_SupplyStack01.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_Banner01.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_WeaponRack02.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_WeaponRack01.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_SupplyStack02.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_Crate02.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_Chair02.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_Poleaxe01.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_Sword01.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_WeaponCrate01.m2
WORLD\EXPANSION07\DOODADS\FORSAKEN\8FK_Forsaken_Table01.m2
world\expansion07\doodads\forsaken\7dl_dalaran_kitchenfire01.blp
world\expansion07\doodads\forsaken\7dl_dalaran_kitchenfire01_glow.blp
world\expansion07\doodads\forsaken\8fk_forsaken_bannermap01b.blp
world\expansion07\doodads\forsaken\8fk_forsaken_bannermap02c.blp
world\expansion07\doodads\forsaken\8fk_forsaken_bannermap02d.blp
world\expansion07\doodads\forsaken\8fk_forsaken_barrelmap02b.blp
world\expansion07\doodads\forsaken\8fk_forsaken_braziermap01.blp
world\expansion07\doodads\forsaken\8fk_forsaken_chairmap01b.blp
world\expansion07\doodads\forsaken\8fk_forsaken_cratemap01.blp
world\expansion07\doodads\forsaken\8fk_forsaken_tablemap01.blp
world\expansion07\doodads\forsaken\ember_offset_streak.blp
world\expansion07\doodads\forsaken\fire_bright_mod2x_a.blp
world\expansion07\doodads\forsaken\genericglow_alpha_128.blp
world\expansion07\doodads\forsaken\t_vfx_fire_anim_stylized_desat_02.blp
world\expansion07\doodads\forsaken\white8x8.blp
world\generic\pvp\warsonggulch\7ne_druid_stonerune01.blp
world\generic\pvp\warsonggulch\7ne_druid_stonerune02.blp
world\generic\pvp\warsonggulch\8wsg_ashenvale_vine_bark.blp
world\generic\pvp\warsonggulch\8wsg_ashenvale_vine_leaves.blp
WORLD\WMO\ZULDAZAR\TROLL\8TR_Zandalari_ShipLarge01_RaidTransport.wmo
WORLD\WMO\ZULDAZAR\TROLL\8TR_Zandalari_ShipMedWrecked01_000_lod1.blp
WORLD\WMO\ZULDAZAR\TROLL\8TR_Zandalari_ShipMedWrecked01_000_lod2.blp
WORLD\WMO\ZULDAZAR\TROLL\8TR_Zandalari_ShipMedWrecked02_000_lod1.blp
WORLD\WMO\ZULDAZAR\TROLL\8TR_Zandalari_ShipMedWrecked02_000_lod2.blp
WORLD\WMO\ZULDAZAR\TROLL\8TR_Zandalari_ShipMedWrecked03_000_lod1.blp
WORLD\WMO\ZULDAZAR\TROLL\8TR_Zandalari_ShipMedWrecked03_000_lod2.blp
CREATURE\PANDERAN_HOTAIRBALLOON_VEHICLE\PANDERAN_HOTAIRBALLOON_VEHICLE_01.BLP
WORLD\WMO\ZULDAZAR\FORSAKEN\8FK_Forsaken_ShipLarge01_000_lod1.blp
WORLD\WMO\ZULDAZAR\FORSAKEN\8FK_Forsaken_ShipLarge01_000_lod2.blp
WORLD\WMO\DUNGEON\ZULDAZARRAID\8DU_ZuldazarRaid_PristineVault01.wmo
Shaders\Compute\cs_5_0\GenerateMips.bls
Shaders\Vertex\vs_5_0\Terrain8_INTERNAL.bls
Shaders\Pixel\mtlfs_1_1\ASSAO_PrepareDepthsAndNormals.bls
Shaders\Pixel\mtlfs_1_1\ASSAO_PrepareDepthsAndNormalsHalf.bls
Shaders\Pixel\mtlfs_1_1\SSAO_Normals.bls
Shaders\Pixel\mtlfs_1_1\WoWEditGrid_Internal.bls
Shaders\Pixel\mtlfs_1_1\WoWEditImpassableSlopes_Internal.bls
Shaders\Pixel\mtlfs_1_1\WoWEditOverLays_Internal.bls
Shaders\Pixel\mtlfs_1_1\WoWEditPathing_Internal.bls
Shaders\Pixel\mtlfs_1_1\WoWEditTerrainBrush_Internal.bls
Shaders\Pixel\ps_4_0\SSAO_Normals.bls
Shaders\Pixel\ps_4_0\WoWEditGrid_Internal.bls
Shaders\Pixel\ps_4_0\WoWEditImpassableSlopes_Internal.bls
Shaders\Pixel\ps_4_0\WoWEditOverLays_Internal.bls
Shaders\Pixel\ps_4_0\WoWEditPathing_Internal.bls
Shaders\Pixel\ps_4_0\WoWEditTerrainBrush_Internal.bls
Shaders\Pixel\ps_5_0\ASSAO_PrepareDepthsAndNormals.bls
Shaders\Pixel\ps_5_0\ASSAO_PrepareDepthsAndNormalsHalf.bls
Shaders\Pixel\ps_5_0\SSAO_Normals.bls
Shaders\Pixel\ps_5_0\Terrain8_INTERNAL.bls
Shaders\Pixel\ps_5_0\WoWEditGrid_Internal.bls
Shaders\Pixel\ps_5_0\WoWEditImpassableSlopes_Internal.bls
Shaders\Pixel\ps_5_0\WoWEditOverLays_Internal.bls
Shaders\Pixel\ps_5_0\WoWEditPathing_Internal.bls
Shaders\Pixel\ps_5_0\WoWEditTerrainBrush_Internal.bls

**Comment by Marlamin** [comment]
Thanks, should be in the new commit!
