### ISSUE TITLE
[BfA]I want to check Uldir's boss modeling.

### ISSUE THREAD

**Issue by xoduddk123** [wowdev/wow-listfile#112]
I am using `listfile.txt` with [Casc Storage](http://www.zezula.net/en/casc/main.html).
I used listfile.txt to get the voice of Uldir's boss(taloc, mother, zek`boz, etc ...)
Thank you.

I want to check the `modeling of Uldir boss` through Casc.
However, with listfiel.txt in the current repository, Uldir's boss modeling is not checked.
For example, modeling of `xavius` in `legion` can be checked in `creature/xavius/*`.

Can Uldir's boss modeling be added to listfile.txt?

I'm sorry I do not have enough English. :)

**Comment by hoxton22** [comment]
Hi, i think all models from the game (.m2) are referenced in the listfile, because when i check all unknows files, the only unknown m2 are testmodel or something like that.
What boss are you looking for, for example ?

**Comment by xoduddk123** [comment]
@hoxton22 
creature/* seems to be a regular NPC.

I want to model all of Uldir's bosses.
```
Taloc
Mother
Zek`boz
Vectis
Fetid Devourer
Zul, Reborn
Mythrax the Unraveler
G'huun
```

**Comment by Qartar** [comment]
@xoduddk123 `creature` contains all NPC, mob, and boss models, however the model names don't always match the name of the creature in game. You may need to hunt around a little bit for the exact models you're looking for.

**Comment by xoduddk123** [comment]
@Qartar 
Then I have to find each path of `creature/*`.
Thinking about meeting all of Wow's `creature` is terrible.

If I find it, I'll report it here... :sob:

**Comment by hoxton22** [comment]
look at creature/aqir/

it look like Mythrax, but i'm not sure about it.

**Comment by Qartar** [comment]
Here is the full list as best as I can tell:

|Boss|Model|
|-- |-- |
|Taloc |`creature/vigo/capturedtitanconstruct.m2`|
|MOTHER|`creature/titanfemalenazmir/titanfemalenazmir.m2`|
|Zek'voz|`creature/aqir/aqir.m2`|
|Vectis|`creature/bloodelemental/bloodelemental.m2`|
|Fetid Devourer|`creature/chimeraboss/chimeraboss.m2`|
|Zul, Reborn|`creature/zul/zul.m2`|
|Mythrax the Unraveler|`creature/kithix/kithix.m2`|
|G'huun|`creature/bloodgod/bloodgod.m2`|

**Comment by xoduddk123** [comment]
@hoxton22 @Qartar 
Thank you. 
I found all the Boss modeling because of you.

@Qartar 
How did you find these?
Do you have any know-how?

**Comment by Qartar** [comment]
@xoduddk123 I looked through the list of models that have been added since Legion for names that I didn't recognize (e.g. aqir, kithix) or looked relevant (e.g. titanfemalenazmir, bloodgod) and opened those up in a model viewer. You can get that list by diffing `listfile.txt` against an earlier version.

**Comment by barncastle** [comment]
You can also use the game's db files. @Marlamin's [site](https://bnet.marlam.in) is pretty feature packed now and is the quickest way but you can also use a DB2 editor. 

To look up a creature's model using his site:
1. Go to ["DBC Viewer"](https://bnet.marlam.in/dbc.php)
2. Select Creature.db2 and the build you're after from the dropdowns
3. Search for the creature's name and note the DisplayIds that aren't 0 (Taloc uses 85386)
4. Change file to CreatureDisplayInfo.db2 and search for each of the above DisplayIds
5. Find the rows with Ids matching the DisplayIds and click the ModelID links, taking note of the FileDataId of each (1980085 in this example)
6. Go to ["Game Files"](https://bnet.marlam.in/files.php) and search for the FileDataIds and hope the names have been found/bruteforced

**Comment by xoduddk123** [comment]
The way @qartar told me is a bit time consuming, but it seems to be the most obvious way.
@barncastle's method is simple, but only for Taloc, Zul, Mythrax the Unraveler, G'huun.

I tried to find the NPC ID in wowhead.
However, this method did not find everything.

Later, if I find a better way, I'll record it here.

Thank you all.
It has helped a lot because of you guys.
