### ISSUE TITLE
Battle for Azeroth 8.1.5 Patch Cinematics unpacking

### ISSUE THREAD

**Issue by Streetx2k7** [wowdev/wow-listfile#113]
Hi guys!

Can you help me with new 8.1.5. BfA patch?

I want to extracting the following cinematic file:
interface/cinematics/bfa_815_dpr_1920.avi

Thanks for the help!

**Comment by bloerwald** [comment]
Hey,

I’m not quite sure how this project is supposed to help here: we provide file names and you obviously have that.

**Comment by Streetx2k7** [comment]
Yep. CascView still didn't working for me with this new listfile. :(

**Comment by bloerwald** [comment]
This is not the cascview issue tracker, so we can’t help with that really.

**Comment by Marlamin** [comment]
As @bloerwald explained this is not the place for this. Key is live on wiki now so CASCView can be updated with the key now. Open an issue in the CASCView repo asking to do so.
