### ISSUE TITLE
How to Find the Voice of the Boss in Dragonflight.

### ISSUE THREAD

**Issue by KwonTae-young** [wowdev/wow-listfile#133]
Hi,

I'm looking for the boss raid voice for Vault of the Incarnates. (CASC Exporer, wow.export)
I had experience writing issues similar to this in BfA in the past.(#112)

I tried to find the Vault of the Incarnates boss voice using the method @barncastle told me in a previous issue.
But I couldn't find the voice of the boss.
It's been 4 years since the previous issue and I think the way to find boss voices has changed in that time.

I know that the name of the boss and the voice of the boss may not match.
Can you tell me how to find the voice of the boss in the dragonflight?
I want to learn how to find the boss voice.

What I was trying to find was the sound of the Kurog Grimtotem.
https://youtu.be/zeZX9u4kE8s

Below is a breakdown of what @barncastle told me to do.  
https://github.com/wowdev/wow-listfile/issues/112#issuecomment-426010535  
<img width="686" alt="image" src="https://user-images.githubusercontent.com/10510127/218535957-e925121b-a96a-4575-86f3-49eb16cd382b.png">

![image](https://user-images.githubusercontent.com/10510127/218536260-f58f2ecb-4d33-42c8-9ceb-b4c48feafb50.png)
If I search for `kurog`, I can find 2 DisplayIDs.(106792, 106356)

| Boss | DisplayID[0] | ModelID | FileDataID |
|---|---|---|---|
| Kurog Grimtotem | 106792 | 7399 | 968705 |
| Kurog Grimtotem | 106356 | 13331 | 4511128 |

</br>
Tab to the file in `wow.tools` and retrieve the FileDataID will create the model with the seek.

![image](https://user-images.githubusercontent.com/10510127/218538116-257a0b6b-5b38-49e9-83b6-43b8162606fc.png)  
`taurenmale_hd` doesn't seem to be.

![image](https://user-images.githubusercontent.com/10510127/218538584-4cc5351f-55c1-4dab-a2ed-c7e2ba74ff7c.png)  
I was able to find part of Kurog Grimtotem's voice in the path of `sound/creature/kurog_grimtotem`.
However, many voices were missing.

Tried it on other bosses too
`Dathea` was not found in Creature.db2.
The same goes for `Diurna`. 
`Raszageth` was found under the name raszagethboss.m2.
But I couldn't find it in the `sound/creature/` path.

I'm sorry I do not have enough English. :)

**Comment by Marlamin** [comment]
That only works if the files are named by the community but nobody has bothered to do so yet.

You can now use WoWHead to find the NPC and then clicking quotes to see the boss speech. Clicking the sounds will get you the filedataid.

e.g. https://www.wowhead.com/npc=184986/kurog-grimtotem

If you manage to make a list of these files for each NPC name you're after feel free to submit a suggestion with the same naming format as the existing names for other NPCs so you and others can find them by name in the future.

**Comment by KwonTae-young** [comment]
Are there tutorials or wikis for beginners?

**Comment by Marlamin** [comment]
For finding files, not really. Just a lot of learning and using tools. For naming files there aren't really tutorials either but sticking with the same structures as existing filenames when coming up with new names is generally enough, then for sending them to this repo you can find out how to do that from the readme file.
