### ISSUE TITLE
CSV listfile suggestion

### ISSUE THREAD

**Issue by natnat201193** [wowdev/wow-listfile#138]
[ListfileSuggestions.txt](https://github.com/wowdev/wow-listfile/files/11072505/ListfileSuggestions.txt)

**Comment by Marlamin** [comment]
Hey! Thanks for these. Some tips for how to improve these in the future:

- Make sure all lines are formatted correctly (one line is missing a `;`)
- Where possible, put things in the folder they "fit" in as to get rid of temporary names altogether*
- Rename related files as well so things remain together (for M2s, most importantly .skin files)*

_*These are partly automated, but humans are far better at it as it always misses a few things._

Will merge these and sort things into their respective folders in a bit, thanks again!
