### ISSUE TITLE
CSV listfile correction

### ISSUE THREAD

**Issue by Endervendetta** [wowdev/wow-listfile#189]
[listfilesuggestions.20230915.txt](https://github.com/wowdev/wow-listfile/files/12622405/listfilesuggestions.20230915.txt)

**Comment by Marlamin** [comment]
Hey, these are official names so we can't override them even if they're wrong. :D

**Comment by Endervendetta** [comment]
Isn't the folder wrong?
current: interface/HUD/inv_scarabmount_green.blp
correction: interface/icons/inv_scarabmount_green.blp

**Comment by Marlamin** [comment]
Yes, but that's Blizzard's error not ours and if there are official filenames we stick with those

**Comment by Endervendetta** [comment]
ok, it makes sense :)
