### ISSUE TITLE
Missing game tables

### ISSUE THREAD

**Issue by Ovahlord** [wowdev/wow-listfile#224]
OCTClassCombatRatingScalar, TeamContributionPoints and OCTBaseHPByClass do exist as gametables within the cata beta client and probably within wotlk classic as well

The cata beta client is loading the following game tables (most of them are also loaded in wotlk)

ShieldBlockRegular
OCTRegenHP
RegenHPPerSpt
OCTRegenMP
RegenMPPerSpt
CombatRatings
NPCManaCostScaler
ChanceToMeleeCritBase
ChanceToMeleeCrit
ChanceToSpellCritBase
ChanceToSpellCrit
OCTBaseHPByClass
OCTBaseMPByClass
OCTHPPerStamina
BarberShopCostBase
OCTClassCombatRatingScalar
TeamContributionPoints
SpellScaling

**Comment by Marlamin** [comment]
What's the exact issue? These all exist in the listfile.

**Comment by Ovahlord** [comment]
yeah, I just figured that. the zezula txt file was outdated. My apologies
