### ISSUE TITLE
11.0.2 Archmage Khadgar lines

### ISSUE THREAD

**Issue by Natans8** [wowdev/wow-listfile#333]
[vo_1102_archmage_khadgar.txt](https://github.com/user-attachments/files/16997232/vo_1102_archmage_khadgar.txt)

**Comment by Marlamin** [comment]
One of those IDs is too big

**Comment by Natans8** [comment]
> One of those IDs is too big

Fixed it
[vo_1102_archmage_khadgar.txt](https://github.com/user-attachments/files/16997294/vo_1102_archmage_khadgar.txt)
